from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from src.output_layout import default_stage_filename, make_stage_dir, write_manifest


NODE_ID_COLUMN = "node_id"
ROLE_COLUMN = "node_role"
BENIGN_LABEL = "BENIGN"
DEFAULT_WINDOW = "1h"
DEFAULT_ANOMALY_THRESHOLD = 0.65
DEFAULT_ROLE_THRESHOLD = 0.65
DEFAULT_MIN_ROLE_TOTAL_FLOWS = 60
DEFAULT_MIN_ROLE_ANOMALY_RATIO = 0.50
DEFAULT_MIN_ROLE_HIGH_CONF_FLOWS = 8
DEFAULT_MIN_DIRECTIONAL_HIGH_CONF_FLOWS = 4
REQUIRED_COLUMNS = {
    "src_ip",
    "dst_ip",
    "timestamp",
    "predicted_label",
    "anomaly_score",
    "is_anomaly",
}
NODE_OUTPUT_COLUMNS: list[str] = [
    NODE_ID_COLUMN,
    "window_start",
    "total_flows",
    "total_anomalous_flows",
    "high_conf_anomalous_flows",
    "anomaly_ratio",
    "avg_anomaly_score",
    "max_anomaly_score",
    "outbound_flows",
    "outbound_anomalous_flows",
    "outbound_high_conf_anomalous_flows",
    "outbound_anomaly_ratio",
    "inbound_flows",
    "inbound_anomalous_flows",
    "inbound_high_conf_anomalous_flows",
    "inbound_anomaly_ratio",
    "outbound_unique_targets",
    "inbound_unique_sources",
    "outbound_unique_target_ports",
    "small_flow_ratio",
    "single_packet_ratio",
    "role_evidence_support",
    "attacker_score",
    "victim_score",
    "compromised_score",
    ROLE_COLUMN,
    "top_predicted_labels",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Aggregate flow-level inference results into node-level anomaly assessments."
    )
    parser.add_argument(
        "--input-path",
        type=Path,
        required=True,
        help="Inference CSV file or directory of CSV files generated by inference.py.",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=None,
        help="Output CSV path. Default: outputs/results/<timestamp>_<input>/node_summary/<input>_node_summary.csv",
    )
    parser.add_argument(
        "--result-dir",
        type=Path,
        default=None,
        help="Dedicated result directory that stores node summaries under <result-dir>/node_summary/.",
    )
    parser.add_argument(
        "--window",
        default=DEFAULT_WINDOW,
        help=f"Pandas time window used for node aggregation. Default: {DEFAULT_WINDOW}",
    )
    parser.add_argument(
        "--anomaly-threshold",
        type=float,
        default=DEFAULT_ANOMALY_THRESHOLD,
        help=(
            "Minimum anomaly score to count a flow as high-confidence anomalous for node scoring. "
            f"Default: {DEFAULT_ANOMALY_THRESHOLD}"
        ),
    )
    parser.add_argument(
        "--role-threshold",
        type=float,
        default=DEFAULT_ROLE_THRESHOLD,
        help=(
            "Minimum role score required before a node is labeled attacker/victim/compromised. "
            f"Default: {DEFAULT_ROLE_THRESHOLD}"
        ),
    )
    parser.add_argument(
        "--min-role-total-flows",
        type=int,
        default=DEFAULT_MIN_ROLE_TOTAL_FLOWS,
        help=(
            "Minimum flows required in a window before any non-uncertain role can be assigned. "
            f"Default: {DEFAULT_MIN_ROLE_TOTAL_FLOWS}"
        ),
    )
    parser.add_argument(
        "--min-role-anomaly-ratio",
        type=float,
        default=DEFAULT_MIN_ROLE_ANOMALY_RATIO,
        help=(
            "Minimum anomalous-flow ratio required in a window before any non-uncertain role can be assigned. "
            f"Default: {DEFAULT_MIN_ROLE_ANOMALY_RATIO}"
        ),
    )
    parser.add_argument(
        "--min-role-high-conf-flows",
        type=int,
        default=DEFAULT_MIN_ROLE_HIGH_CONF_FLOWS,
        help=(
            "Minimum high-confidence anomalous flows required in a window before any non-uncertain role can be assigned. "
            f"Default: {DEFAULT_MIN_ROLE_HIGH_CONF_FLOWS}"
        ),
    )
    parser.add_argument(
        "--min-directional-high-conf-flows",
        type=int,
        default=DEFAULT_MIN_DIRECTIONAL_HIGH_CONF_FLOWS,
        help=(
            "Minimum high-confidence anomalous flows required in the decisive direction "
            "(outbound for attacker, inbound for victim, both for compromised). "
            f"Default: {DEFAULT_MIN_DIRECTIONAL_HIGH_CONF_FLOWS}"
        ),
    )
    return parser.parse_args()


def discover_csv_inputs(input_path: Path) -> list[Path]:
    if input_path.is_file():
        return [input_path]
    if input_path.is_dir():
        files = sorted(input_path.glob("*.csv"))
        if not files:
            raise FileNotFoundError(f"No CSV files found in {input_path}")
        return files
    raise FileNotFoundError(f"Input path does not exist: {input_path}")


def validate_output_args(output_path: Path | None, result_dir: Path | None) -> None:
    if output_path is not None and result_dir is not None:
        raise ValueError("Use either --output-path or --result-dir, not both.")


def ensure_output_path(output_path: Path | None, input_path: Path, result_dir: Path | None) -> Path:
    if output_path is not None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        return output_path
    stage_dir = make_stage_dir(input_path=input_path, stage="node_summary", result_dir=result_dir)
    return stage_dir / default_stage_filename(input_path, "node_summary")


def load_inference_dataframe(input_files: list[Path]) -> pd.DataFrame:
    frames = [pd.read_csv(path, low_memory=False) for path in input_files]
    if not frames:
        raise RuntimeError("No inference CSVs were loaded.")
    df = pd.concat(frames, ignore_index=True)
    missing = sorted(REQUIRED_COLUMNS.difference(df.columns))
    if missing:
        raise KeyError(f"Missing required columns for node summary: {missing}")
    return df


def normalize_inference_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    frame = df.copy()
    frame["timestamp"] = pd.to_datetime(frame["timestamp"], errors="coerce")
    frame["is_anomaly"] = frame["is_anomaly"].astype(str).str.lower().map(
        {"true": True, "false": False}
    )
    frame["is_anomaly"] = frame["is_anomaly"].fillna(False)
    frame["anomaly_score"] = pd.to_numeric(frame["anomaly_score"], errors="coerce").fillna(0.0)
    frame["predicted_label"] = frame["predicted_label"].astype(str).fillna(BENIGN_LABEL)
    frame["src_ip"] = frame["src_ip"].astype(str)
    frame["dst_ip"] = frame["dst_ip"].astype(str)
    if "Destination Port" in frame.columns:
        frame["Destination Port"] = pd.to_numeric(frame["Destination Port"], errors="coerce")
    if "Total Fwd Packets" in frame.columns:
        frame["Total Fwd Packets"] = pd.to_numeric(frame["Total Fwd Packets"], errors="coerce")
    if "Total Backward Packets" in frame.columns:
        frame["Total Backward Packets"] = pd.to_numeric(frame["Total Backward Packets"], errors="coerce")
    if "Total Length of Fwd Packets" in frame.columns:
        frame["Total Length of Fwd Packets"] = pd.to_numeric(
            frame["Total Length of Fwd Packets"], errors="coerce"
        )
    if "Total Length of Bwd Packets" in frame.columns:
        frame["Total Length of Bwd Packets"] = pd.to_numeric(
            frame["Total Length of Bwd Packets"], errors="coerce"
        )
    return frame.dropna(subset=["timestamp"])


def build_directed_flow_views(df: pd.DataFrame) -> pd.DataFrame:
    common_columns = [column for column in df.columns if column not in {NODE_ID_COLUMN}]
    outbound = df[common_columns].copy()
    outbound[NODE_ID_COLUMN] = outbound["src_ip"]
    outbound["direction"] = "outbound"
    outbound["counterparty_ip"] = outbound["dst_ip"]
    outbound["counterparty_port"] = outbound.get("Destination Port", np.nan)

    inbound = df[common_columns].copy()
    inbound[NODE_ID_COLUMN] = inbound["dst_ip"]
    inbound["direction"] = "inbound"
    inbound["counterparty_ip"] = inbound["src_ip"]
    inbound["counterparty_port"] = inbound.get("src_port", np.nan)
    return pd.concat([outbound, inbound], ignore_index=True)


def top_labels_for_group(group: pd.DataFrame, limit: int = 3) -> str:
    anomalous = group[group["predicted_label"] != BENIGN_LABEL]
    if anomalous.empty:
        return BENIGN_LABEL
    counts = anomalous["predicted_label"].value_counts().head(limit)
    return "; ".join(f"{label}:{count}" for label, count in counts.items())


def capped_support(value: int | float, minimum: int | float) -> float:
    if minimum <= 0:
        return 1.0 if value > 0 else 0.0
    return min(1.0, float(value) / float(minimum))


def score_node(
    window_group: pd.DataFrame,
    threshold: float,
    role_threshold: float,
    min_role_total_flows: int,
    min_role_anomaly_ratio: float,
    min_role_high_conf_flows: int,
    min_directional_high_conf_flows: int,
) -> tuple[float, float, float, str, int, int, int, float]:
    outbound = window_group[window_group["direction"] == "outbound"]
    inbound = window_group[window_group["direction"] == "inbound"]

    outbound_ratio = float(outbound["is_anomaly"].mean()) if not outbound.empty else 0.0
    inbound_ratio = float(inbound["is_anomaly"].mean()) if not inbound.empty else 0.0
    anomaly_ratio = float(window_group["is_anomaly"].mean()) if not window_group.empty else 0.0

    high_conf_out = outbound[outbound["anomaly_score"] >= threshold]
    high_conf_in = inbound[inbound["anomaly_score"] >= threshold]
    high_conf_out_count = int(len(high_conf_out))
    high_conf_in_count = int(len(high_conf_in))
    high_conf_total = high_conf_out_count + high_conf_in_count

    outbound_target_spread = (
        high_conf_out["counterparty_ip"].nunique() / max(1, len(high_conf_out))
        if not high_conf_out.empty
        else 0.0
    )
    inbound_source_spread = (
        high_conf_in["counterparty_ip"].nunique() / max(1, len(high_conf_in))
        if not high_conf_in.empty
        else 0.0
    )
    window_support = capped_support(len(window_group), min_role_total_flows) * capped_support(
        high_conf_total, min_role_high_conf_flows
    )
    outbound_support = window_support * capped_support(high_conf_out_count, min_directional_high_conf_flows)
    inbound_support = window_support * capped_support(high_conf_in_count, min_directional_high_conf_flows)

    attacker_score = min(
        1.0,
        0.40 * outbound_ratio
        + 0.25 * float(high_conf_out["anomaly_score"].mean() if not high_conf_out.empty else 0.0)
        + 0.10 * outbound_target_spread
        + 0.25 * outbound_support,
    )
    victim_score = min(
        1.0,
        0.40 * inbound_ratio
        + 0.25 * float(high_conf_in["anomaly_score"].mean() if not high_conf_in.empty else 0.0)
        + 0.10 * inbound_source_spread
        + 0.25 * inbound_support,
    )

    overlap = min(outbound_ratio, inbound_ratio)
    compromised_score = min(
        1.0,
        0.30 * overlap
        + 0.25 * float(window_group["anomaly_score"].mean())
        + 0.20 * anomaly_ratio
        + 0.125 * outbound_support
        + 0.125 * inbound_support,
    )

    meets_global_evidence = (
        len(window_group) >= min_role_total_flows
        and anomaly_ratio >= min_role_anomaly_ratio
        and high_conf_total >= min_role_high_conf_flows
    )
    meets_outbound_evidence = meets_global_evidence and high_conf_out_count >= min_directional_high_conf_flows
    meets_inbound_evidence = meets_global_evidence and high_conf_in_count >= min_directional_high_conf_flows
    meets_bidir_evidence = meets_outbound_evidence and meets_inbound_evidence

    role = "uncertain"
    if compromised_score >= role_threshold and meets_bidir_evidence and outbound_ratio > 0 and inbound_ratio > 0:
        role = "suspected_compromised_host"
    elif (
        attacker_score >= max(victim_score, compromised_score)
        and attacker_score >= role_threshold
        and meets_outbound_evidence
    ):
        role = "suspected_attacker"
    elif (
        victim_score >= max(attacker_score, compromised_score)
        and victim_score >= role_threshold
        and meets_inbound_evidence
    ):
        role = "suspected_victim"

    return (
        attacker_score,
        victim_score,
        compromised_score,
        role,
        high_conf_total,
        high_conf_out_count,
        high_conf_in_count,
        window_support,
    )


def summarize_nodes(
    df: pd.DataFrame,
    window: str,
    anomaly_threshold: float,
    role_threshold: float,
    min_role_total_flows: int = DEFAULT_MIN_ROLE_TOTAL_FLOWS,
    min_role_anomaly_ratio: float = DEFAULT_MIN_ROLE_ANOMALY_RATIO,
    min_role_high_conf_flows: int = DEFAULT_MIN_ROLE_HIGH_CONF_FLOWS,
    min_directional_high_conf_flows: int = DEFAULT_MIN_DIRECTIONAL_HIGH_CONF_FLOWS,
) -> pd.DataFrame:
    directed = build_directed_flow_views(df)
    normalized_window = window.strip().lower()
    directed["window_start"] = directed["timestamp"].dt.floor(normalized_window)

    rows: list[dict[str, object]] = []
    for (node_id, window_start), group in directed.groupby([NODE_ID_COLUMN, "window_start"], sort=True):
        outbound = group[group["direction"] == "outbound"]
        inbound = group[group["direction"] == "inbound"]

        (
            attacker_score,
            victim_score,
            compromised_score,
            role,
            high_conf_total,
            high_conf_out_count,
            high_conf_in_count,
            role_evidence_support,
        ) = score_node(
            group,
            threshold=anomaly_threshold,
            role_threshold=role_threshold,
            min_role_total_flows=min_role_total_flows,
            min_role_anomaly_ratio=min_role_anomaly_ratio,
            min_role_high_conf_flows=min_role_high_conf_flows,
            min_directional_high_conf_flows=min_directional_high_conf_flows,
        )

        total_packets = (
            group.get("Total Fwd Packets", pd.Series(dtype=float)).fillna(0)
            + group.get("Total Backward Packets", pd.Series(dtype=float)).fillna(0)
        )
        total_bytes = (
            group.get("Total Length of Fwd Packets", pd.Series(dtype=float)).fillna(0)
            + group.get("Total Length of Bwd Packets", pd.Series(dtype=float)).fillna(0)
        )

        rows.append(
            {
                NODE_ID_COLUMN: node_id,
                "window_start": window_start,
                "total_flows": len(group),
                "total_anomalous_flows": int(group["is_anomaly"].sum()),
                "high_conf_anomalous_flows": high_conf_total,
                "anomaly_ratio": float(group["is_anomaly"].mean()),
                "avg_anomaly_score": float(group["anomaly_score"].mean()),
                "max_anomaly_score": float(group["anomaly_score"].max()),
                "outbound_flows": len(outbound),
                "outbound_anomalous_flows": int(outbound["is_anomaly"].sum()) if not outbound.empty else 0,
                "outbound_high_conf_anomalous_flows": high_conf_out_count,
                "outbound_anomaly_ratio": float(outbound["is_anomaly"].mean()) if not outbound.empty else 0.0,
                "inbound_flows": len(inbound),
                "inbound_anomalous_flows": int(inbound["is_anomaly"].sum()) if not inbound.empty else 0,
                "inbound_high_conf_anomalous_flows": high_conf_in_count,
                "inbound_anomaly_ratio": float(inbound["is_anomaly"].mean()) if not inbound.empty else 0.0,
                "outbound_unique_targets": int(outbound["counterparty_ip"].nunique()) if not outbound.empty else 0,
                "inbound_unique_sources": int(inbound["counterparty_ip"].nunique()) if not inbound.empty else 0,
                "outbound_unique_target_ports": (
                    int(pd.to_numeric(outbound["counterparty_port"], errors="coerce").nunique())
                    if not outbound.empty
                    else 0
                ),
                "small_flow_ratio": float((total_bytes <= 200).mean()) if len(group) else 0.0,
                "single_packet_ratio": float((total_packets <= 1).mean()) if len(group) else 0.0,
                "role_evidence_support": role_evidence_support,
                "attacker_score": attacker_score,
                "victim_score": victim_score,
                "compromised_score": compromised_score,
                ROLE_COLUMN: role,
                "top_predicted_labels": top_labels_for_group(group),
            }
        )

    summary = pd.DataFrame(rows, columns=NODE_OUTPUT_COLUMNS)
    if summary.empty:
        return summary
    return summary.sort_values(
        by=["window_start", "compromised_score", "attacker_score", "victim_score", "anomaly_ratio"],
        ascending=[True, False, False, False, False],
    ).reset_index(drop=True)


def main() -> None:
    args = parse_args()
    validate_output_args(args.output_path, args.result_dir)
    input_files = discover_csv_inputs(args.input_path)
    output_path = ensure_output_path(args.output_path, args.input_path, args.result_dir)
    df = normalize_inference_dataframe(load_inference_dataframe(input_files))
    summary = summarize_nodes(
        df,
        window=args.window,
        anomaly_threshold=args.anomaly_threshold,
        role_threshold=args.role_threshold,
        min_role_total_flows=args.min_role_total_flows,
        min_role_anomaly_ratio=args.min_role_anomaly_ratio,
        min_role_high_conf_flows=args.min_role_high_conf_flows,
        min_directional_high_conf_flows=args.min_directional_high_conf_flows,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_path, index=False, encoding="utf-8-sig")
    if args.output_path is None:
        write_manifest(
            output_path.parent.parent / "node_summary_manifest.json",
            {
                "script": "node_summary.py",
                "input_path": str(args.input_path),
                "output_root": str(output_path.parent.parent),
                "node_summary_csv": str(output_path),
                "source_files": [str(path) for path in input_files],
                "nodes_summarized": int(len(summary)),
                "window": args.window,
                "anomaly_threshold": args.anomaly_threshold,
                "role_threshold": args.role_threshold,
                "min_role_total_flows": args.min_role_total_flows,
                "min_role_anomaly_ratio": args.min_role_anomaly_ratio,
                "min_role_high_conf_flows": args.min_role_high_conf_flows,
                "min_directional_high_conf_flows": args.min_directional_high_conf_flows,
            },
        )
    print(f"Input files: {len(input_files)}")
    print(f"Output CSV: {output_path}")
    print(f"Nodes summarized: {len(summary)}")
    print(f"Role threshold: {args.role_threshold}")
    print(
        "Role evidence: "
        f"min_total_flows={args.min_role_total_flows}, "
        f"min_anomaly_ratio={args.min_role_anomaly_ratio}, "
        f"min_high_conf_flows={args.min_role_high_conf_flows}, "
        f"min_directional_high_conf_flows={args.min_directional_high_conf_flows}"
    )


if __name__ == "__main__":
    main()
